process.env.ACCOUNT_RATE_MAX = '1000';
process.env.COMPLAINTS_EMAIL = 'complaints@usvistra.com';
const fs = require('fs'); const path = require('path'); const crypto = require('crypto');
const { FakeIO } = require('./harness');
const logs = []; const origLog = console.log;
console.log = (...a) => { const s = a.join(' '); logs.push(s); if (!/\[email:mock\]|\[storage\]|\[push\]/.test(s)) origLog(...a); };
const lastCode = (re) => { for (let i = logs.length - 1; i >= 0; i--) { const m = logs[i].match(re); if (m) return m[1]; } return null; };
let pass = 0, fail = 0;
const ok = (c, msg) => { if (c) { pass++; origLog('  ✓', msg); } else { fail++; origLog('  ✗ FAIL:', msg); } };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const section = (s) => origLog('\n' + s);

function fakeImage(name, w, h, size) {
  const buf = Buffer.alloc(size, 0); crypto.randomBytes(size).copy(buf);
  Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0, 0, 0, 13, 0x49, 0x48, 0x44, 0x52]).copy(buf, 0);
  buf.writeUInt32BE(w, 16); buf.writeUInt32BE(h, 20);
  fs.writeFileSync(path.join(__dirname, '..', 'uploads', name), buf); return '/uploads/' + name;
}

(async () => {
  const { initStore, store } = require('../db');
  await initStore();
  const { registerSocketHandlers } = require('../socketHandlers');
  const tracking = require('../tracking');
  const T = require('../trackingDefs');
  const io = new FakeIO();

  const admin = io.add('9.9.9.9'); registerSocketHandlers(io, admin);
  const buyer = io.add('2.2.2.2'); registerSocketHandlers(io, buyer);
  const seller = io.add('1.1.1.1'); registerSocketHandlers(io, seller);

  section('1. Admin creates a group with the seller email pre-filled');
  await admin.fire('join-room', { groupId: 'default-group', role: 'PARTY A', adminKey: 'SUPERADMIN123', sessionToken: 'admin-token' });
  await admin.fire('create-group', { groupName: 'Test Deal', emailB: 'seller@example.com', emailA: 'buyer@example.com' });
  const gid = admin.last('group-created-and-switch').newGroupId;
  ok(!!gid, 'group created: ' + gid);
  await buyer.fire('join-room', { groupId: gid, role: 'BUYER', sessionToken: 'buyer-token' });
  const buyerInit = buyer.last('init-state');
  ok(buyerInit.group.emails.B === null && buyerInit.group.emails.A === 'buyer@example.com', 'buyer only receives their own email (not the seller\'s)');
  await seller.fire('join-room', { groupId: gid, role: 'SELLER', sessionToken: 'seller-token', lang: 'fr' });
  const sInit = seller.last('init-state');
  ok(sInit.group.emails.B === 'seller@example.com' && sInit.group.emails.A === null, 'seller receives the pre-filled email for the registration box (and nothing else)');

  section('2. Registration requires verified email + terms + phone');
  const base = { groupId: gid, fullName: 'Kwame Mensah', password: 'Sup3rSecret!', currency: 'USD', dateOfBirth: '1990-05-04', country: 'Ghana', phoneDial: '233', phoneNumber: '0244 123 456', language: 'fr', acceptTerms: true, accountType: 'standard', email: 'seller@example.com' };
  await seller.fire('register-transaction-account', base);
  ok(/verify your email/i.test(seller.last('error-msg') || ''), 'registration blocked until email verified');
  await seller.fire('request-registration-email-code', { groupId: gid, email: 'seller@example.com' });
  ok(!!seller.last('registration-email-code-sent'), 'email code sent');
  const code = lastCode(/>>> (\d{6}) <<</);
  ok(/^\d{6}$/.test(code || ''), 'code present in (mock) email: ' + code);
  await seller.fire('verify-registration-email', { groupId: gid, email: 'seller@example.com', code: '000000' });
  ok(seller.last('registration-email-result').ok === false, 'wrong code rejected');
  await seller.fire('verify-registration-email', { groupId: gid, email: 'seller@example.com', code });
  ok(seller.last('registration-email-result').ok === true, 'correct code accepted');
  await seller.fire('register-transaction-account', { ...base, acceptTerms: false });
  ok(/accept the Terms/i.test(seller.last('error-msg')), 'terms checkbox is mandatory');
  await seller.fire('register-transaction-account', { ...base, phoneNumber: '12' });
  ok(/valid phone/i.test(seller.last('error-msg')), 'invalid phone rejected');
  await seller.fire('register-transaction-account', { ...base, accountType: 'business' });
  ok(/Standard/i.test(seller.last('error-msg')), 'only Standard accounts can be created at registration');
  await seller.fire('register-transaction-account', base);
  const created = seller.last('transaction-account-created');
  ok(created && /^[1-9]\d{10}$/.test(created.accountId), 'account created with 11-digit Account ID ' + (created && created.accountId));
  let g = await store.getGroup(gid);
  ok(g.seller_phone === '+233244123456', 'phone stored in E.164: ' + g.seller_phone);
  ok(g.seller_country === 'Ghana' && g.seller_country_iso === 'GH', 'country + ISO saved');
  ok(g.seller_account_type === 'standard' && g.seller_language === 'fr' && g.seller_email_locked === true, 'standard type, language and email lock saved');
  ok(g.seller_terms_accepted_at && g.seller_terms_version, 'terms acceptance + version recorded');
  ok(JSON.stringify(g.seller_ip_log).includes('1.1.1.1'), 'registration IP recorded');
  await seller.fire('set-my-email', { groupId: gid, email: 'other@example.com' });
  ok(/cannot be changed/i.test(seller.last('error-msg')), 'seller email can never be changed');
  await admin.fire('admin-set-party-email', { groupId: gid, party: 'B', email: 'x@example.com' });
  ok(/cannot be changed/i.test(admin.last('error-msg')), 'admin cannot change it either');
  const acct = seller.last('seller-account-state');
  ok(acct.accountId === created.accountId && acct.accountTypeLabel === 'Standard account', 'account state exposes Account ID + type label');
  const adminView = (await new Promise(async (res) => { await admin.fire('admin-get-seller-profile', { groupId: gid }); res(admin.last('seller-profile')); })).account;
  ok(adminView.fullName === 'Kwame Mensah' && adminView.phone === '+233244123456' && adminView.country === 'Ghana' && adminView.passwordSet === true && !JSON.stringify(adminView).includes('Sup3rSecret'), 'admin sees saved name/country/phone; password never exposed');

  section('2b. Same email already used by another account → registration still allowed');
  await admin.fire('create-group', { groupName: 'Second Deal', emailB: 'seller@example.com' });
  const gid2 = admin.last('group-created-and-switch').newGroupId;
  const seller3 = io.add('3.3.3.3'); registerSocketHandlers(io, seller3);
  await seller3.fire('join-room', { groupId: gid2, role: 'SELLER', sessionToken: 'seller-token-3' });
  await seller3.fire('request-registration-email-code', { groupId: gid2, email: 'seller@example.com' });
  ok(!!seller3.last('registration-email-code-sent') && !seller3.last('error-msg'), 'code is sent even though that email already owns another account');
  const code3 = lastCode(/>>> (\d{6}) <<</);
  await seller3.fire('verify-registration-email', { groupId: gid2, email: 'seller@example.com', code: code3 });
  await seller3.fire('register-transaction-account', { ...base, groupId: gid2, password: 'Other#Pass12' });
  ok(!!seller3.last('transaction-account-created'), 'second account registers successfully on the same email');

  section('2c. Staff password viewing');
  const vault = require('../vault');
  g = await store.getGroup(gid);
  ok(g.seller_password_enc && !g.seller_password_enc.includes('Sup3rSecret') && (await vault.decrypt(g.seller_password_enc)) === 'Sup3rSecret!', 'password stored encrypted (not plain), decryptable by the vault');
  const adminProfile0 = require('../finance').publicSellerAccount(g, { forAdmin: true });
  ok(!JSON.stringify(adminProfile0).includes('Sup3rSecret') && adminProfile0.passwordStored === true, 'profile payload never carries the password itself');
  const adm2 = io.add('8.8.8.8'); registerSocketHandlers(io, adm2);
  await adm2.fire('join-room', { groupId: gid, role: 'PARTY A', adminKey: 'ADMIN123', sessionToken: 'admin2-token' });
  const mod = io.add('8.8.4.4'); registerSocketHandlers(io, mod);
  await mod.fire('join-room', { groupId: gid, role: 'PARTY A', adminKey: 'MODERATOR123', sessionToken: 'mod-token' });
  await adm2.fire('admin-reveal-seller-password', { groupId: gid });
  ok(adm2.last('seller-password-revealed') && adm2.last('seller-password-revealed').password === 'Sup3rSecret!', 'any Admin can open the seller password (v3.2)');
  await mod.fire('admin-reveal-seller-password', { groupId: gid });
  ok(!mod.last('seller-password-revealed'), 'moderators can never see it');
  await adm2.fire('admin-set-password-access', { groupId: gid, allowed: true });
  ok(!!adm2.last('error-msg') && !(await store.getGroup(gid)).password_admin_access, 'only the company (Super Admin) can assign access');
  await admin.fire('admin-set-password-access', { groupId: gid, allowed: true });
  await adm2.fire('admin-reveal-seller-password', { groupId: gid });
  ok(true, 'assignment no longer needed');
  await admin.fire('admin-reveal-seller-password', { groupId: gid });
  ok(admin.last('seller-password-revealed') && admin.last('seller-password-revealed').password === 'Sup3rSecret!', 'the company (Super Admin) can always open it');
  g = await store.getGroup(gid); ok(g.seller_password_reveals.length >= 2, 'every reveal is written to the audit log');
  await admin.fire('admin-set-password-access', { groupId: gid, allowed: false });
  ok(true, 'password access is by role now');
  ok(!buyer.all('seller-password-revealed').length && !seller.all('seller-password-revealed').length, 'buyers and sellers never receive it');

  section('2d. Email provider failure is shown to the seller');
  { const E = require('../email'); const prevEnv = process.env.NODE_ENV; process.env.NODE_ENV = 'production'; E.setRuntimeConfig(null);
    const sellerX = io.add('4.4.4.4'); registerSocketHandlers(io, sellerX);
    await admin.fire('create-group', { groupName: 'Third Deal', emailB: 'third@example.com' }); const gid3 = admin.last('group-created-and-switch').newGroupId;
    await sellerX.fire('join-room', { groupId: gid3, role: 'SELLER', sessionToken: 'seller-token-x' });
    await sellerX.fire('request-registration-email-code', { groupId: gid3, email: 'third@example.com' });
    ok(sellerX.last('registration-email-failed') && /not set up/i.test(sellerX.last('registration-email-failed').message) && !sellerX.last('registration-email-code-sent'), 'no provider → seller is told the email service is not set up (not left waiting)');
    process.env.EMAIL_DEV_ECHO_CODES = 'true'; delete require.cache[require.resolve('../accountHandlers')];
    process.env.NODE_ENV = prevEnv; }

  section('3. KYC: automatic, moderate validation');
  const front = fakeImage('t-front.png', 1000, 700, 60000), back = fakeImage('t-back.png', 1000, 700, 60000), proof = fakeImage('t-proof.png', 900, 1200, 90000), selfie = fakeImage('t-selfie.png', 640, 640, 50000);
  const goodKyc = { groupId: gid, docType: 'national_id', idFrontUrl: front, idBackUrl: back, proofAddressType: 'utility_bill', proofAddressUrl: proof, selfieUrl: selfie, idNumber: 'GHA-123456789-1', idName: 'Kwame Mensah', idDob: '1990-05-04', idExpiry: '2032-01-01', quality: { idFront: { blurry: false }, idBack: { blurry: false } }, face: { detected: true, method: 'faceapi', live: true } };
  await seller.fire('submit-kyc', { ...goodKyc, idExpiry: '2020-01-01' });
  let r = seller.last('kyc-auto-result');
  ok(r.passed === false && r.reasons.some((x) => /expired/i.test(x)), 'expired ID auto-rejected with a reason');
  g = await store.getGroup(gid); ok(g.kyc_status === 'rejected', 'status set to rejected');
  await seller.fire('submit-kyc', { ...goodKyc, idName: 'Peter Smith', face: { detected: false, method: 'native' } });
  r = seller.last('kyc-auto-result');
  ok(r.passed === false && r.reasons.some((x) => /name/i.test(x)) && r.reasons.some((x) => /face/i.test(x)), 'wrong name + browser sees no face → both reasons shown');
  await seller.fire('submit-kyc', { ...goodKyc, idNumber: '000000000' });
  r = seller.last('kyc-auto-result'); ok(r.passed === false && r.reasons.some((x) => /ID number/i.test(x)), 'fake ID number rejected');
  await seller.fire('submit-kyc', { ...goodKyc, idName: 'Kwame Kofi Mensah' });
  r = seller.last('kyc-auto-result'); ok(r.passed === true, 'valid details (extra middle name) pass — moderate, not strict');
  await store.updateGroup(gid, { kyc_status: 'none' });
  const { idName, idDob, ...slim } = goodKyc;
  await seller.fire('submit-kyc', { ...slim, face: { detected: false, method: 'colour' } });
  r = seller.last('kyc-auto-result'); ok(r.passed === false && r.reasons.some((x) => /real human face/i.test(x)), 'a selfie with no real face (poster / wall) is rejected');
  await store.updateGroup(gid, { kyc_status: 'none' });
  await seller.fire('submit-kyc', { ...slim, face: { detected: true, method: 'faceapi', live: false } });
  r = seller.last('kyc-auto-result'); ok(r.passed === false && r.reasons.some((x) => /live person/i.test(x)), 'a live capture without the blink / head-turn check is rejected');
  await store.updateGroup(gid, { kyc_status: 'none' });
  await seller.fire('submit-kyc', { ...slim, face: { detected: true, method: 'faceapi', live: true } });
  r = seller.last('kyc-auto-result'); ok(r.passed === true, 'real, live face + ID number and expiry → accepted');
  await store.updateGroup(gid, { kyc_status: 'none' });
  await seller.fire('submit-kyc', { ...slim, face: { detected: true, method: 'faceapi', live: true, tooDark: true } });
  r = seller.last('kyc-auto-result'); ok(r.passed === false && r.reasons.some((x) => /too dark/i.test(x)), 'a clearly too-dark selfie is still sent back');
  await store.updateGroup(gid, { kyc_status: 'none' });
  await seller.fire('submit-kyc', { ...goodKyc, idName: 'Kwame Kofi Mensah' });
  g = await store.getGroup(gid); ok(g.kyc_status === 'pending', 'valid submission goes to Desk review');
  await admin.fire('admin-review-kyc', { groupId: gid, decision: 'verified' });
  g = await store.getGroup(gid); ok(g.kyc_status === 'verified', 'admin verified KYC');

  section('4. Incoming funds → live tracking → automatic release');
  await admin.fire('admin-record-incoming-funds', { groupId: gid, payerName: 'ACME Corp', purpose: 'Invoice 42', method: 'bank_transfer', amount: 50000, amountCurrency: 'USD', feeAmount: 100, feePayer: 'buyer', treatment: 'track', totalSeconds: 120, internalNote: 'Checked wire slip', shareNoteWithBuyer: true, bankName: 'Barclays', senderAccount: 'GB29NWBK60161331926819', externalRef: 'REF-1' });
  const recd = admin.last('incoming-funds-recorded'); ok(!!recd, 'incoming funds recorded ' + (recd && recd.ref));
  g = await store.getGroup(gid);
  ok(Number(g.balance_held) === 50000 && Number(g.balance_available) === 0, 'buyer pays the charge on top: the seller\'s full 50,000.00 is in the vault');
  ok(buyer.all('message').some((m) => /DESK NOTE/.test(m.text)), 'shared internal note appears in the group for the buyer');
  let snap = seller.last('seller-account-snapshot') || seller.last('seller-state');
  const inc = (await store.getIncomingFundsForGroup(gid))[0];
  ok(inc.track_enabled && inc.track_stage === 1, 'tracker started at stage 1');
  const pubSeller = require('../finance').publicIncoming(inc, false, g.seller_account_id);
  ok(!JSON.stringify(pubSeller.track).includes('timerSec') && pubSeller.track.stages[2].checks === undefined, 'seller payload: no timers, no detail on queued stages');
  ok(!('internalNote' in pubSeller), 'seller payload: no internal note');
  // fast-forward: speed 100000x then tick
  await admin.fire('admin-tracking-set', { id: inc.id, speed: 86400, timers: [2, 2, 2, 2, 2, 2] });
  const eng = tracking.startTrackingEngine(io, 100000);
  let guard = 0; let cur;
  while (guard++ < 40) { await sleep(60); await eng.tick(); cur = await store.getIncomingFundsById(inc.id); if (cur.track_stage > require('../trackingDefs').STAGE_COUNT) break; }
  eng.stop();
  ok(cur.status === 'held_in_vault' && cur.track_stage > 6, 'after the last stage the funds STAY in the vault, awaiting the Desk');
  g = await store.getGroup(gid);
  ok(Number(g.balance_held) === 50000 && Number(g.balance_available) === 0, 'nothing released automatically');
  await admin.fire('admin-update-incoming-funds', { id: inc.id, action: 'release' });
  cur = await store.getIncomingFundsById(inc.id); g = await store.getGroup(gid);
  ok(cur.status === 'credited' && Number(g.balance_available) === 50000 && Number(g.balance_held) === 0, 'admin releases from the vault → main account');
  const stage4 = require('../trackingDefs').STAGES[3].checks[1].replace('{ACCOUNT_ID}', g.seller_account_id);
  const adminTrack = require('../finance').publicIncoming(cur, true, g.seller_account_id);
  ok(adminTrack.track === null || adminTrack.track.complete === true, 'tracker marked complete');
  ok(stage4 === `Funds transferred to the seller account ${g.seller_account_id}`, 'stage 4 text uses the real Account ID: "' + stage4 + '"');

  section('5. Disbursement gate + withdrawal with email code');
  const wd = { groupId: gid, method: 'bank', amount: 1000, beneficiaryName: 'Kwame Mensah', bankName: 'GCB', bankAccount: '1234567890', bankSwift: 'GHCBGHAC', bankCountry: 'Ghana' };
  await seller.fire('request-withdrawal', wd);
  let blk = seller.last('withdrawal-blocked');
  ok(blk && blk.reason === 'disbursement', 'withdrawal blocked: not in disbursement stage');
  await admin.fire('admin-set-disbursement', { groupId: gid, enabled: true });
  ok(buyer.all('disbursement-updated').length > 0 && buyer.all('message').some((m) => /DISBURSEMENT/.test(m.text)), 'disbursement stage shown in the group for both parties');
  await seller.fire('request-withdrawal', wd);
  ok(!!seller.last('withdrawal-code-sent'), 'withdrawal code emailed');
  const wcode = lastCode(/>>> (\d{6}) <<</);
  await seller.fire('confirm-withdrawal', { groupId: gid, code: '111111' });
  ok(seller.last('withdrawal-confirm-result').ok === false, 'wrong code rejected');
  await seller.fire('confirm-withdrawal', { groupId: gid, code: wcode });
  const cr = seller.last('withdrawal-confirm-result'); ok(cr.ok === true, 'withdrawal created after email code ' + cr.ref);
  g = await store.getGroup(gid);
  ok(Number(g.balance_available) === 49000 && Number(g.balance_pending) === 1000, 'money left available and went straight to pending');
  const w1 = (await store.getWithdrawalsForGroup(gid))[0];
  ok(w1.request_ip === '1.1.1.1' && w1.seller_account_id === g.seller_account_id, 'withdrawal stores IP + Account ID');
  await admin.fire('admin-advance-withdrawal', { withdrawalId: w1.id, toStatus: 'processing' });
  g = await store.getGroup(gid); ok(Number(g.balance_pending) === 1000, 'processing keeps funds pending');
  await admin.fire('admin-advance-withdrawal', { withdrawalId: w1.id, toStatus: 'declined', reason: 'Bank details mismatch' });
  g = await store.getGroup(gid); ok(Number(g.balance_available) === 50000 && Number(g.balance_pending) === 0, 'declined returned funds to available');
  await admin.fire('admin-advance-withdrawal', { withdrawalId: w1.id, toStatus: 'pending', reason: 'Re-opened after fix' });
  g = await store.getGroup(gid); ok(Number(g.balance_pending) === 1000 && Number(g.balance_available) === 49000, 'any stage selectable: declined → pending re-reserves funds');
  await admin.fire('admin-advance-withdrawal', { withdrawalId: w1.id, toStatus: 'completed' });
  g = await store.getGroup(gid); ok(Number(g.balance_pending) === 0 && Number(g.balance_available) === 49000, 'completed: money gone from pending');
  const done = await store.getWithdrawalById(w1.id); ok(done.status === 'completed', 'status stored as completed (shown as Completed, not credited)');

  section('6. Daily 10,000,000 limit → Business upgrade → unlimited');
  await admin.fire('admin-record-incoming-funds', { groupId: gid, payerName: 'Big Buyer', purpose: 'Large order', method: 'wire', amount: 30000000, amountCurrency: 'USD', treatment: 'credit' });
  await seller.fire('request-withdrawal', { ...wd, amount: 10000001 });
  blk = seller.last('withdrawal-blocked'); ok(blk && blk.reason === 'daily_limit', 'over 10,000,000/day blocked → ' + (blk && blk.title));
  const bizBase = { groupId: gid, companyName: 'Mensah Trading Ltd', legalForm: 'Ltd', registrationNumber: 'CS123456', registrationCountry: 'Ghana', incorporationDate: '2015-03-02', taxId: 'C0012345678', businessAddress: '12 Ring Road Central', city: 'Accra', postalCode: 'GA-100', businessType: 'Import and export of electronics', directorName: 'Kwame Mensah', uboName: 'Kwame Mensah', monthlyVolume: '$10M – $50M', sourceOfFunds: 'Revenue from electronics wholesale', declaration: true, certUrl: proof, taxDocUrl: front, addressDocUrl: back };
  await seller.fire('submit-business-upgrade', { ...bizBase, taxId: '1' });
  ok(/tax identification/i.test(seller.last('error-msg')), 'business form validates tax ID');
  await seller.fire('submit-business-upgrade', bizBase);
  ok(!!seller.last('business-submitted-ok'), 'business application submitted');
  await admin.fire('admin-review-business', { groupId: gid, decision: 'verified' });
  g = await store.getGroup(gid); ok(g.seller_account_type === 'business' && g.business_status === 'verified', 'approved → Business account');
  await seller.fire('request-withdrawal', { ...wd, amount: 12000000 });
  ok(!!seller.last('withdrawal-code-sent'), 'business account may withdraw above 10,000,000');

  section('7. Crypto prior-deposit requirement');
  await seller.fire('request-withdrawal', { groupId: gid, method: 'crypto', asset: 'USDT', network: 'TRC20', destination: 'TXyzABCDEFGH1234567', amount: 5000, amountCurrency: 'USD' });
  blk = seller.last('withdrawal-blocked');
  ok(blk && blk.reason === 'crypto_deposit' && Math.abs(blk.requiredUsd - 1000) < 0.01, 'tier 1 (<$10k): 20% of $5,000 = $1,000 required → got ' + (blk && blk.requiredUsd));
  await seller.fire('notify-deposit', { groupId: gid, asset: 'USDT', network: 'TRC20', amount: 1000 });
  const dep = (await store.getDepositsForGroup(gid))[0];
  ok(!!dep, 'crypto deposit notified');
  await admin.fire('admin-review-deposit', { depositId: dep.id, decision: 'verified' });
  g = await store.getGroup(gid); ok(g.crypto_deposit_verified === true, 'deposit verified → one-time unlock flag set');
  const blockedBefore = seller.all('withdrawal-blocked').length, sentBefore = seller.all('withdrawal-code-sent').length;
  await seller.fire('request-withdrawal', { groupId: gid, method: 'crypto', asset: 'USDT', network: 'TRC20', destination: 'TXyzABCDEFGH1234567', amount: 5000000, amountCurrency: 'USD' });
  ok(seller.all('withdrawal-blocked').length === blockedBefore && seller.all('withdrawal-code-sent').length === sentBefore + 1, 'after unlock, even a large crypto withdrawal skips the tier check');

  section('8. Disable / enable seller account');
  await admin.fire('admin-set-seller-disabled', { groupId: gid, disabled: true, reason: 'Compliance review' });
  ok(seller.last('seller-access-changed').disabled === true && seller.last('seller-access-changed').complaintsEmail === 'complaints@usvistra.com', 'seller notified: disabled + complaints email');
  await seller.fire('request-withdrawal', wd); ok(/disabled/i.test(seller.last('error-msg')), 'disabled seller cannot withdraw');
  ok(logs.some((l) => /has been disabled/.test(l) && /complaints@usvistra\.com/.test(l)), 'disable email mentions complaints@usvistra.com');
  await admin.fire('admin-set-seller-disabled', { groupId: gid, disabled: false });
  ok(seller.last('seller-access-changed').disabled === false, 'seller notified: re-enabled');

  section('9. IP detection + admin IP block');
  g = await store.getGroup(gid); ok(JSON.stringify(g.seller_ip_log).includes('1.1.1.1'), 'IP log has seller IP');
  await admin.fire('admin-set-ip-block', { groupId: gid, ip: '1.1.1.1', blocked: true });
  const seller2 = io.add('1.1.1.1'); registerSocketHandlers(io, seller2);
  await seller2.fire('join-room', { groupId: gid, role: 'SELLER', sessionToken: 'seller-token-2' });
  ok(!!seller2.last('ip-blocked') && !seller2.last('init-state'), 'blocked IP cannot join as seller');
  await admin.fire('admin-set-ip-block', { groupId: gid, ip: '1.1.1.1', blocked: false });

  section('10. Messages notify everyone, reminders, read sync');
  const notifier = require('../notifier');
  const before = admin.all('alert').length;
  await seller.fire('send-message', { groupId: gid, text: 'Hello team, shipment is ready' });
  ok(buyer.all('alert').some((a) => a.kind === 'message') , 'buyer alerted live');
  ok(admin.all('alert').length > before || (await store.getUnreadCounts('admin-token'))[gid] >= 1, 'admin alerted / unread counted');
  ok((await store.getUnreadCounts('buyer-token'))[gid] >= 1, 'buyer unread count incremented');
  ok(notifier._reminders.has('buyer-token|' + gid), 'reminder clock started for buyer');
  const rows = await store.getAllUnreadRows(); ok(rows.length >= 2, 'unread rows tracked for reminders');
  notifier._reminders.get('buyer-token|' + gid).lastAt = Date.now() - 61 * 60 * 1000;
  const nb = buyer.all('alert').length; await notifier.runReminders(io);
  ok(buyer.all('alert').length === nb + 1 && buyer.last('alert').reminder === true, 'reminder fired after 60 minutes');
  await buyer.fire('mark-group-read', { groupId: gid });
  ok(seller.all('message-read-by').length > 0 && !JSON.stringify(seller.all('message-read-by')).includes('buyer-token'), 'sender told that the buyer read it (without leaking the buyer\'s session token)');
  ok(!notifier._reminders.has('buyer-token|' + gid), 'buyer reminders stopped once read');

  section('11. No session tokens on the wire');
  { const wire = JSON.stringify([...io.log, ...buyer.emitted, ...seller.emitted, ...seller3.emitted]);
    ok(!/buyer-token|seller-token|admin-token|admin2-token|mod-token/.test(wire.replace(/"sessionToken":"[^"]*"/g, '')), 'no one\'s session token appears in anything sent to the group (except each person\'s own init-state)');
    const msgs = buyer.all('message'); ok(msgs.length > 0 && msgs.every((m) => !('senderToken' in m) && (m.senderId === null || /^u_[A-Za-z0-9_-]{22}$/.test(m.senderId))), 'messages carry an opaque senderId, not senderToken');
    const pres = buyer.all('presence-update').flat(); ok(pres.length > 0 && pres.every((u) => !('sessionToken' in u) && /^u_/.test(u.uid)), 'presence list carries opaque ids only');
    const init = buyer.last('init-state'); const { uidOf } = require('../identity'); ok(init.uid === uidOf('buyer-token'), 'a person receives their own opaque id at join (to recognise their own messages)'); }
  { const adminDm = io.add('7.7.7.7'); registerSocketHandlers(io, adminDm);
    await adminDm.fire('join-room', { groupId: gid, role: 'PARTY A', adminKey: 'ADMIN123', sessionToken: 'admin3-token' });
    const { uidOf } = require('../identity');
    await adminDm.fire('admin-initiate-dm', { targetUid: uidOf('buyer-token'), initialMessage: 'Hello buyer' });
    const opened = buyer.last('dm-channel-opened'); ok(opened && !/buyer-token|admin3-token/.test(opened.dmRoomId), 'DM room id is opaque (no tokens in it)');
    const n0 = buyer.all('dm-message').length; await seller.fire('send-dm-reply', { dmRoomId: opened.dmRoomId, text: 'intruder' });
    ok(buyer.all('dm-message').length === n0, 'someone outside the DM channel cannot post into it');
    await buyer.fire('send-dm-reply', { dmRoomId: opened.dmRoomId, text: 'Hi desk' }); ok(buyer.all('dm-message').length === n0 + 1, 'channel members can reply');
    await adminDm.fire('admin-initiate-dm', { targetUid: 'u_notarealuserid000000', initialMessage: 'x' }); ok(true, 'unknown ids are ignored'); }
  origLog(`\nRESULT: ${pass} passed, ${fail} failed`);
  process.exit(fail ? 1 : 0);
})().catch((e) => { origLog('FATAL', e); process.exit(2); });
