import json, sys, time
from playwright.sync_api import sync_playwright
fx = json.load(open('/tmp/fixtures.json'))
gid = fx['gid']
errors = []; passed = 0; failed = 0
def ok(c, msg):
    global passed, failed
    if c: passed += 1; print('  ✓', msg)
    else: failed += 1; print('  ✗ FAIL:', msg)
def replay(page, events):
    for ev, data in events:
        page.evaluate("([e,d]) => window.__srv.emit(e,d)", [ev, data])
def sent(page, name):
    return page.evaluate("(n) => (window.__sent||[]).filter(x => x[0]===n).map(x => x[1])", name)

with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={'width': 400, 'height': 860}, permissions=[])
    page = ctx.new_page()
    page.on('pageerror', lambda e: errors.append('PAGEERROR ' + str(e)))
    page.on('response', lambda r: errors.append('HTTP404 ' + r.url) if r.status == 404 else None)
    page.on('console', lambda m: errors.append('CONSOLE ' + m.text) if m.type == 'error' and 'flagcdn' not in m.text and 'font' not in m.text.lower() and 'ERR_' not in m.text else None)
    ctx.add_init_script("localStorage.setItem('q_onboarded','1')")
    page.route('**/cdnjs.cloudflare.com/**', lambda r: r.abort())
    page.route('**/fonts.g*apis.com/**', lambda r: r.abort())
    page.route('**/flagcdn.com/**', lambda r: r.abort())
    page.route('**/fonts.gstatic.com/**', lambda r: r.abort())
    page.goto(f'http://localhost:8099/?groupId={gid}&role=SELLER', wait_until='domcontentloaded')
    page.wait_for_timeout(500)
    print('\nA. Boot + join'); ok(len(errors) == 0, 'no JS errors on load: ' + str(errors[:3]))
    j = sent(page, 'join-room'); ok(len(j) >= 1 and j[0].get('lang'), 'join-room carries the chosen language: ' + str(j[0].get('lang') if j else None))

    print('\nB. Registration form')
    replay(page, fx['s1_join']); page.wait_for_timeout(300)
    ok(page.is_visible('#txRegModal'), 'registration modal opens for an unregistered seller')
    ok(page.input_value('#txRegEmailInput') == 'seller@example.com', 'seller email auto-filled from the group link')
    ok(page.is_visible('#txRegEmailPrefillNote'), 'prefill note visible')
    ok('can never be changed' in page.inner_text('#txRegModal'), 'permanent-email warning is shown')
    ok(page.input_value('#txRegAccountType') == 'standard' and 'Standard account' in page.inner_text('#txRegModal'), '"Standard account" selected automatically')
    page.click('#txRegEmailClear'); ok(page.input_value('#txRegEmailInput') == '', 'seller can remove the auto-filled email')
    page.fill('#txRegEmailInput', 'seller@example.com')
    # password eye
    page.fill('#txRegPasswordInput', 'Sup3rSecret!')
    ok(page.get_attribute('#txRegPasswordInput', 'type') == 'password', 'password hidden by default')
    page.click('#txRegPasswordInput + .pw-eye'); ok(page.get_attribute('#txRegPasswordInput', 'type') == 'text', 'eye button reveals the password')
    page.fill('#txRegPasswordConfirmInput', 'Different1!'); ok('do not match' in page.inner_text('#txRegPwMatch'), 'mismatch flagged live')
    page.fill('#txRegPasswordConfirmInput', 'Sup3rSecret!'); ok('match' in page.inner_text('#txRegPwMatch'), 'match confirmed live')
    # country picker
    page.click('#txRegCountryBtn'); page.wait_for_timeout(100)
    n_all = page.locator('#countryList .picker-item').count(); ok(n_all >= 190, f'country list holds all countries ({n_all})')
    ok(page.evaluate("() => { const l=document.getElementById('countryList'); return l.scrollHeight > l.clientHeight && getComputedStyle(l).overflowY==='auto' }"), 'country list is scrollable')
    page.fill('#countrySearch', 'ghan'); ok(page.locator('#countryList .picker-item').first.inner_text().startswith('Ghana') and page.locator('#countryList .picker-item').count() < 5, 'typing "ghan" narrows the list instantly, Ghana first')
    page.fill('#countrySearch', '+44'); ok('United Kingdom' in page.inner_text('#countryList'), 'dial code search works (+44)')
    page.fill('#countrySearch', 'ghan'); page.click('#countryList .picker-item')
    ok('Ghana' in page.inner_text('#txRegCountryText'), 'country chosen'); ok(page.inner_text('#txRegDialText') == '+233', 'phone prefix follows the country (+233)')
    # submit without terms
    page.fill('#txRegNameInput', 'Kwame Mensah'); page.fill('#txRegPhoneInput', '0244123456'); page.fill('#txRegDobInput', '1990-05-04')
    page.evaluate("() => { window.__sent = []; }")
    page.click('#txRegSubmitBtn'); page.wait_for_timeout(150)
    ok(len(sent(page, 'register-transaction-account')) == 0, 'blocked until email verified')
    ok('verify your email' in page.inner_text('#toastContainer').lower() if page.locator('#toastContainer').count() else True, 'tells the seller to verify the email')
    page.click('#txRegSendCodeBtn'); ok(len(sent(page, 'request-registration-email-code')) == 1, 'send-code emits to server')
    replay(page, fx['s2_codesent']); page.wait_for_timeout(100)
    ok(page.is_visible('#txRegCodeRow'), 'code box appears')
    page.fill('#txRegCodeInput', fx['regCode']); page.click('#txRegCodeRow .send-btn')
    ok(sent(page, 'verify-registration-email')[0]['code'] == fx['regCode'], 'verify emits the typed code')
    replay(page, fx['s3_verified']); page.wait_for_timeout(100)
    ok(page.is_visible('#txRegEmailVerified'), '"Email verified" badge shown')
    page.click('#txRegSubmitBtn'); page.wait_for_timeout(150)
    ok(len(sent(page, 'register-transaction-account')) == 0, 'blocked until terms checkbox ticked')
    page.click('#txRegTerms'); page.click('#txRegSubmitBtn'); page.wait_for_timeout(150)
    reg = sent(page, 'register-transaction-account'); ok(len(reg) == 1, 'registration submitted after ticking terms')
    if reg: r = reg[0]; ok(r['phoneDial'] == '233' and r['country'] == 'Ghana' and r['acceptTerms'] is True and r['accountType'] == 'standard' and r['fullName'] == 'Kwame Mensah', 'payload has phone, country, terms, standard type')
    # terms modal
    page.click('#txRegModal .terms-check a'); page.wait_for_timeout(300)
    ok('Handling of funds' in page.inner_text('#termsBody') and 'complaints@usvistra.com' in page.inner_text('#termsBody'), 'full terms render (incl. complaints email)')
    page.click('#termsModal .send-btn'); ok(not page.is_visible('#termsModal'), 'terms modal closes on "I agree"')

    print('\nC. After registration → next-step popup')
    replay(page, fx['s4_registered']); page.wait_for_timeout(300)
    ok(page.is_visible('#nextStepModal'), 'next-step window pops up')
    ok('Start transaction' in page.inner_text('#nextStepModal') and 'Continue KYC verification' in page.inner_text('#nextStepModal'), 'offers both options')
    acct = json.loads(json.dumps(fx['s4_registered']))
    aid = [d for e, d in fx['s4_registered'] if e == 'seller-account-state'][-1]['accountId']
    ok(aid in page.inner_text('#nextStepAccountId'), 'shows the new Account ID ' + aid)
    page.click('#nextStepModal .next-card >> nth=0'); page.wait_for_timeout(200)
    ok(not page.is_visible('#nextStepModal') and not page.is_visible('#txAccountView'), '"Start transaction" lands in the group chat')
    page.evaluate("() => openTxAccountView()"); page.wait_for_timeout(300)
    ok(aid in page.inner_text('#txAcctIdLabel'), 'Account ID shown on the dashboard under the currency')
    ok('Ghana' in page.inner_text('#txCountryPill') and page.locator('#txCountryFlag img, #txCountryFlag .flag-emoji').count() == 1, 'country shown with its flag')
    ok('Account ID' in page.inner_text('.tx-currency-pill.acct-id-pill'), 'label reads "Account ID"')

    print('\nD. Live tracking (seller sees stages, no timers)')
    replay(page, fx['s5_tracking']); page.wait_for_timeout(300)
    ok(page.is_visible('#txLiveTrackPanel'), 'live payment panel appears on the dashboard')
    html = page.inner_html('#txLiveTrackList')
    ok('in_review' in html and 'trk-stage' in html, 'an in-review stage is rendered')
    ok(page.locator('#txLiveTrackList .trk-stage.in_review .trk-pill').count() == 1, 'exactly one stage is the active (blinking) one')
    anim = page.evaluate("() => getComputedStyle(document.querySelector('#txLiveTrackList .trk-stage.in_review .trk-pill')).animationName")
    ok('trkBlink' in anim, 'active stage pill has the blink animation: ' + anim)
    txt = page.inner_text('#txLiveTrackList')
    ok('Queued' in txt or 'Passed' in txt, 'passed/queued labels visible')
    ok(not any(w in txt for w in ['d 0h', 'h 0m', ' left']), 'no timers or "left" text shown to the seller')
    ok('2,000,000.00' in page.inner_text('#txAvailableBalance') or '$0.00' in page.inner_text('#txAvailableBalance'), 'amounts use grouped formatting')
    replay(page, fx['s6_credited']); page.wait_for_timeout(300)
    ok('1,999,500.00' in page.inner_text('#txAvailableBalance'), 'after release, balance shows elite format $1,999,500.00')
    ok(not page.is_visible('#txLiveTrackPanel'), 'live panel hides once the funds are released')
    stage4 = fx['s5_tracking'] and [d for e, d in fx['s5_tracking'] if e == 'incoming-list' or e == 'seller-account-snapshot']
    page.evaluate("() => setTxAccountNav('transactions')"); page.wait_for_timeout(150)
    ok('Net $1,999,500.00' in page.inner_text('#txIncomingList') or 'Fee' in page.inner_text('#txIncomingList'), 'incoming list shows fee / net details')

    print('\nE. Withdraw page, gates and popups')
    page.evaluate("() => setTxAccountNav('withdraw')"); page.wait_for_timeout(250)
    ok(page.input_value('#txWithdrawMethod') == '', 'withdraw form starts clean (no cached method)')
    ok('Unlimited' in page.inner_text('#wdUnlimitedLink'), '"Unlimited withdrawals" option is visible')
    ok('1,999,500.00' in page.inner_text('#wdAvail'), 'available balance shown')
    page.evaluate("() => { const s=document.getElementById('txWithdrawMethod'); s.value='bank'; s.dispatchEvent(new Event('change',{bubbles:true})); }")
    page.fill('#txWdBeneficiary', 'K Mensah'); page.fill('#txWdBankName', 'GCB'); page.fill('#txWdBankAccount', '1234567890'); page.fill('#txWdAmount', '100')
    page.evaluate("() => { window.__sent=[]; }")
    page.click('#txWdSubmit'); ok(sent(page, 'request-withdrawal')[0]['method'] == 'bank', 'withdrawal request emitted')
    replay(page, fx['s7_blocked']); page.wait_for_timeout(250)
    ok(page.is_visible('#wdBlockedModal') and 'disbursement' in page.inner_text('#wdBlockedModal').lower(), 'popup: transaction not yet in disbursement stage')
    ok('Complete transaction' in page.inner_text('#wdBlockedActions'), 'popup has "Complete transaction" button')
    page.click('#wdBlockedActions .send-btn'); page.wait_for_timeout(200)
    ok(not page.is_visible('#txAccountView') and not page.is_visible('#wdBlockedModal'), 'click takes the seller to the transaction group')
    # code step
    replay(page, [e for e in fx['s8_codesent']]); page.wait_for_timeout(250)
    ok(page.is_visible('#wdCodeModal') and 'security code' in page.inner_text('#wdCodeModal').lower(), 'email-code confirmation window opens')
    page.fill('#wdCodeInput', fx['wdCode']); page.evaluate("() => { window.__sent=[]; }")
    page.click('#wdCodeModal .send-btn'); ok(sent(page, 'confirm-withdrawal')[0]['code'] == fx['wdCode'], 'confirm emits the code')
    replay(page, fx['s9_withdrawn']); page.wait_for_timeout(250)
    ok(not page.is_visible('#wdCodeModal'), 'code window closes after success')
    page.evaluate("() => { openTxAccountView(); setTxAccountNav('withdraw'); }"); page.wait_for_timeout(250)
    card = page.inner_text('#txWithdrawalsOnlyBody')
    ok('pending' in card.lower() and 'date created' in card.lower() and 'account id' in card.lower(), 'withdrawal record shows status, date created and Account ID')
    ok(page.locator('#txWithdrawalsOnlyBody .wd-step.active').count() == 1, 'exactly one blinking step (Pending)')
    ok(page.evaluate("() => getComputedStyle(document.querySelector('#txWithdrawalsOnlyBody .wd-step.active .bub i')).animationName").find('trkBlink') >= 0, 'step icon blinks')
    ok(page.input_value('#txWithdrawMethod') == '', 'bank form is empty again after submitting (cache cleared)')
    replay(page, fx['s10_processing']); page.wait_for_timeout(200)
    ok('Processing' in page.inner_text('#txWithdrawalsOnlyBody'), 'admin moved it to Processing → seller sees Processing')

    print('\nF. Disabled account')
    replay(page, fx['s11_disabled']); page.wait_for_timeout(300)
    ok(page.is_visible('#disabledOverlay'), 'disabled window appears')
    t = page.inner_text('#disabledOverlay')
    ok('complaints@usvistra.com' in t and 'Compliance review' in t, 'shows the reason and complaints@usvistra.com')

    print('\nG. Language & whole-UI translation')
    page.evaluate("() => closeModal('disabledOverlay')")
    page.evaluate("() => document.getElementById('langBtn').click()"); page.wait_for_timeout(150)
    ok(page.is_visible('#languageModal') and page.locator('#languageList .picker-item').count() >= 50, 'language picker lists 50+ languages')
    page.fill('#languageSearch', 'span'); ok('Español' in page.inner_text('#languageList'), 'language search finds Spanish by name')
    page.click('#languageList .picker-item'); page.wait_for_timeout(1200)
    ok(page.evaluate("() => QI18N.lang") == 'es', 'language switched')
    ok('«es»' in page.inner_text('#txPageWithdraw') or '«es»' in page.inner_text('body'), 'interface text is translated')
    ok(page.evaluate("() => document.documentElement.lang") == 'es', '<html lang> updated')
    ok(any(x['language'] == 'es' for x in sent(page, 'set-my-language')), 'preference saved to the account (set-my-language)')
    amt = page.inner_text('#txAvailableBalance'); ok('«' not in amt, 'money values are never altered by translation')
    page.evaluate("() => QI18N.setLanguage('ar')"); page.wait_for_timeout(900)
    ok(page.evaluate("() => document.documentElement.dir") == 'rtl', 'Arabic switches the layout to right-to-left')
    page.evaluate("() => QI18N.setLanguage('en')"); page.wait_for_timeout(500)
    ok('«' not in page.inner_text('#txPageWithdraw'), 'switching back to English restores the original text')

    print('\nH. Notifications')
    page.evaluate("() => { window.__srv.emit('alert', {kind:'message', reminder:false, groupId:'other', groupName:'X', title:'New message from Ama', body:'Hello there'}) }")
    page.wait_for_timeout(200)
    ok('New message from Ama' in page.inner_text('body'), 'alert shows a toast')
    beeps = page.evaluate("() => { let n=0; const C=window.AudioContext||window.webkitAudioContext; return typeof C }")
    ok(beeps != 'undefined', 'audio engine available for the 3x chime')
    page.evaluate("() => window.__srv.emit('message-read-by', {groupId: activeGroupId, readerName:'Desk Officer', readerRole:'ADMINISTRATOR', isAdmin:true})")
    page.wait_for_timeout(150); ok('Desk Officer has read' in page.inner_text('body'), 'read-receipt notice shown to others')

    print('\nI. Sign-in / forgot password UI')
    page.evaluate("() => document.getElementById('signinBtn').click()"); ok(page.is_visible('#loginModal'), 'sign-in window opens'); page.evaluate("() => showForgot()")
    ok(page.is_visible('#loginStepForgot'), 'forgot-password step shows')

    print('\nJ. Admin dashboard')
    ap = ctx.new_page()
    ap.on('pageerror', lambda e: errors.append('ADMIN PAGEERROR ' + str(e)))
    ap.route('**/cdnjs.cloudflare.com/**', lambda r: r.abort()); ap.route('**/flagcdn.com/**', lambda r: r.abort())
    ap.route('**/fonts.g*apis.com/**', lambda r: r.abort()); ap.route('**/fonts.gstatic.com/**', lambda r: r.abort())
    ap.goto(f'http://localhost:8099/?officer=1&groupId={gid}', wait_until='load'); ap.wait_for_timeout(400)
    replay(ap, [('init-state', fx['adminInit'])]); ap.wait_for_timeout(300)
    replay(ap, [('funds-overview', fx['fundsOverview'])]); ap.wait_for_timeout(200)
    ok('Mensah' in ap.inner_text('#fundsDeskList') or 'Kwame' in ap.inner_text('#fundsDeskList'), 'Funds Desk lists the seller')
    fd = ap.inner_text('#fundsDeskList')
    ok('ID ' in fd and ap.locator('#fundsDeskList .flag, #fundsDeskList .flag-emoji').count() >= 1, 'row shows Account ID and the country flag')
    ap.evaluate("(g) => openFundsDeskModal(g)", gid); replay(ap, [('funds-desk-ledger', fx['adminLedgerTracking'])]); ap.wait_for_timeout(300)
    bar = ap.inner_text('#ledgerAdminBar')
    ok('Disable account' in bar and 'disbursement' in bar.lower() and 'Profile' in bar, 'admin bar: disable/enable, disbursement toggle, profile')
    ok(ap.locator('#ledgerAdminBar .flag, #ledgerAdminBar .flag-emoji').count() >= 1, 'country flag beside the seller')
    inc = ap.inner_text('#ledgerIncomingList')
    ok('Barclays' in inc and 'Fee' in inc and 'Wire verified' in inc, 'incoming row has bank, fee/net and internal note')
    ok('Visible to buyer' in inc, 'note flagged as visible to the buyer')
    ok('Skip stage' in inc and 'Timers' in inc, 'tracker controls (pause/skip/timers) present')
    ap.evaluate("(i) => openTrackerModal(i)", fx['adminLedgerTracking']['incoming'][0]['id']); ap.wait_for_timeout(200)
    ok(ap.locator('#trkBody .dur-row').count() == 5 and 'Speed up time' in ap.inner_text('#trkBody'), 'tracker modal: 5 stages in d/h/m/s + speed')
    ap.evaluate("() => { window.__sent=[]; saveTrackerModal(); }"); ok(len(ap.evaluate("() => window.__sent.filter(x=>x[0]==='admin-tracking-set')")) == 1, 'saving emits admin-tracking-set')
    ap.evaluate("() => closeModal('trackerModal')")
    replay(ap, [('funds-desk-ledger', fx['adminLedgerFinal'])]); ap.wait_for_timeout(250)
    wd = ap.inner_text('#ledgerWithdrawalsList')
    ok('Pending' in wd and 'Completed' in wd and 'Declined' in wd, 'withdrawal offers all stages to choose (Pending/Completed/Declined)')
    ok('1.1.1.1' in wd, 'withdrawal shows the requester IP')
    ap.evaluate("(g) => openSellerProfile(g)", gid); replay(ap, [('seller-profile', fx['adminProfile'])]); ap.wait_for_timeout(250)
    sp = ap.inner_text('#spBody')
    ok('Kwame Mensah' in sp and '+233244123456' in sp and 'ghana' in sp.lower() and 'seller@example.com' in sp and 'May 4, 1990' in sp, 'profile: name, phone, country, email saved')
    ok('hashed' in sp and 'Sup3rSecret' not in sp, 'password is shown as set/hashed — never in clear')
    ok('Block IP' in sp and '1.1.1.1' in sp, 'IP log with Block IP control')
    ap.evaluate("() => closeModal('sellerProfileModal'); closeModal('fundsDeskModal')")
    ap.evaluate("() => { fundsDeskGroupId = '%s'; fundsOverviewCache = [{groupId:'%s', sellerName:'Kwame', currency:'USD'}]; openRecordFundsModal(); }" % (gid, gid)); ap.wait_for_timeout(200)
    ok(ap.is_visible('#recordFundsModal') and 'Share this note' not in '' and 'Let the buyer see this note' in ap.inner_text('#recordFundsModal'), 'record-funds: buyer-visibility option for the internal note')
    ok(ap.input_value('#rfTreatment') == 'track' and ap.is_visible('#rfTrackBox'), 'record-funds: tracking on by default')
    ap.select_option('#rfMethod', 'crypto'); ok(ap.is_visible('#rfCryptoFields') and not ap.is_visible('#rfBankFields'), 'crypto fields swap in for bank fields')
    b.close()

print('\nJS errors:', errors if errors else 'none')
print(f'\nRESULT: {passed} passed, {failed} failed')
sys.exit(1 if failed or errors else 0)
